demo/Models/Cart.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace demo.Models
{
    public class Cart
    {
        public tbl_Product item = new tbl_Product();
        public int amounts = 0;
        public int cost = 0;

        public Cart()
        {
            this.item = null;
            this.amounts = 0;
            this.cost = 0;
        }
        public Cart(Cart oldCart)
        {
            if(oldCart!=null)
            {
                this.item = oldCart.item;
                this.amounts = oldCart.amounts;
                this.cost = oldCart.cost;
            }
        }
         public Cart(tbl_Product item)
        {
            this.amounts++;
            if (item.discount > 0) this.cost = item.discount; else this.cost = item.price;
            this.item = item;
        }
        public Cart(tbl_Product item, int num)
        {
            this.amounts+=num;
            if (item.discount > 0) this.cost = item.discount; else this.cost = item.price;
            this.item = item;
        }
    }
}

demo/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using demo.Models;

namespace demo.Controllers
{
    public class AdminController : Controller
    {
        private DemoEntities db = new DemoEntities();
        //GET: Home
        public ActionResult Home()
        {
            if (Session["admin"] == null) return RedirectToAction("Login");
            ViewBag.cus = db.tbl_Customer.ToList();
            ViewBag.bill = db.tbl_Bill.Where(b=>b.level_status == 3).ToList();
            ViewBag.p = db.tbl_Product.Where(p=>p.amount==0).ToList();
            return View("../adminHome");
        }
        // GET: Admin
        public ActionResult Index()
        {
            if (Session["admin"]==null) return RedirectToAction("Login");
            return View(db.tbl_Admin.ToList());
        }
        //GET: Login
        public ActionResult Login()
        {
            return View("../_Login");
        }
        //POST: Login
        [HttpPost]
        public ActionResult postLogin()
        {
            String username = Request.Form.Get("username");
            String pass = Request.Form.Get("pass");
            List<tbl_Admin> adList = db.tbl_Admin.ToList();
            tbl_Admin admin = null;
            foreach (tbl_Admin a in adList)
            {
                if (a.username != username || a.pass != pass)
                    return RedirectToAction("Login");
                admin = a;
                Session["admin"] = admin;
                return RedirectToAction("Home");
            }
            return Redirect(Request.UrlReferrer.AbsoluteUri);
        }
        //GET: Logout
        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Login");
        }
        // GET: Admin/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["admin"] == null) return RedirectToAction("Login");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Admin tbl_Admin = db.tbl_Admin.Find(id);
            if (tbl_Admin == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Admin);
        }

        // GET: Admin/Create
        public ActionResult Create()
        {
            if (Session["admin"] == null) return RedirectToAction("Login");
            return View();
        }

        // POST: Admin/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,username,pass,name")] tbl_Admin tbl_Admin)
        {
            if (Session["admin"] == null) return RedirectToAction("Login");
            if (ModelState.IsValid)
            {
                db.tbl_Admin.Add(tbl_Admin);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tbl_Admin);
        }

        // GET: Admin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["admin"] == null) return RedirectToAction("Login");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Admin tbl_Admin = db.tbl_Admin.Find(id);
            if (tbl_Admin == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Admin);
        }

        // POST: Admin/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,username,pass,name")] tbl_Admin tbl_Admin)
        {
            if (Session["admin"] == null) return RedirectToAction("Login");
            if (ModelState.IsValid)
            {
                db.Entry(tbl_Admin).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tbl_Admin);
        }

        // GET: Admin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["admin"] == null) return RedirectToAction("Login");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Admin tbl_Admin = db.tbl_Admin.Find(id);
            if (tbl_Admin == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Admin);
        }

        // POST: Admin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Session["admin"] == null) return RedirectToAction("Login");
            tbl_Admin tbl_Admin = db.tbl_Admin.Find(id);
            db.tbl_Admin.Remove(tbl_Admin);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

demo/Controllers/BillController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using demo.Models;

namespace demo.Controllers
{
    public class BillController : Controller
    {
        private DemoEntities db = new DemoEntities();

        // GET: Bill
        public ActionResult Index()
        {
            if (Session["admin"] == null) return RedirectToAction("Login");
            var tbl_Bill = db.tbl_Bill.Include(t => t.tbl_Customer);
            return View(tbl_Bill.ToList());
        }
        //GET: Login
        public ActionResult Login()
        {
            return View("../_Login");
        }

        // GET: Bill/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["admin"] == null) return RedirectToAction("Login");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Bill tbl_Bill = db.tbl_Bill.Find(id);
            if (tbl_Bill == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Bill);
        }

        // GET: Bill/Create
        public ActionResult Create()
        {
            if (Session["admin"] == null) return RedirectToAction("Login");
            ViewBag.cus_id = new SelectList(db.tbl_Customer, "id", "username");
            return View();
        }

        // POST: Bill/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,level_status,cus_id,created_at,total_price,cus_name")] tbl_Bill tbl_Bill)
        {
            if (Session["admin"] == null) return RedirectToAction("Login");
            if (ModelState.IsValid)
            {
                db.tbl_Bill.Add(tbl_Bill);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.cus_id = new SelectList(db.tbl_Customer, "id", "username", tbl_Bill.cus_id);
            return View(tbl_Bill);
        }

        // GET: Bill/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["admin"] == null) return RedirectToAction("Login");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Bill tbl_Bill = db.tbl_Bill.Find(id);
            if (tbl_Bill == null)
            {
                return HttpNotFound();
            }
            ViewBag.cus_id = new SelectList(db.tbl_Customer, "id", "username", tbl_Bill.cus_id);
            return View(tbl_Bill);
        }

        // POST: Bill/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,level_status,cus_id,created_at,total_price,cus_name")] tbl_Bill tbl_Bill)
        {
            if (Session["admin"] == null) return RedirectToAction("Login");
            if (ModelState.IsValid)
            {
                db.Entry(tbl_Bill).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.cus_id = new SelectList(db.tbl_Customer, "id", "username", tbl_Bill.cus_id);
            return View(tbl_Bill);
        }

        // GET: Bill/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["admin"] == null) return RedirectToAction("Login");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Bill tbl_Bill = db.tbl_Bill.Find(id);
            if (tbl_Bill == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Bill);
        }

        // POST: Bill/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Session["admin"] == null) return RedirectToAction("Login");
            tbl_Bill tbl_Bill = db.tbl_Bill.Find(id);
            db.tbl_Bill.Remove(tbl_Bill);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

demo/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using demo.Models;

namespace demo.Controllers
{
    public class CategoryController : Controller
    {
        private DemoEntities db = new DemoEntities();

        // GET: Category
        public ActionResult Index()
        {
            if (Session["admin"] == null) return RedirectToAction("Login");
            var tbl_Category = db.tbl_Category.Include(t => t.tbl_Publisher);
            return View(tbl_Category.ToList());
        }
        //GET: Login
        public ActionResult Login()
        {
            return View("../_Login");
        }

        // GET: Category/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["admin"] == null) return RedirectToAction("Login");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Category tbl_Category = db.tbl_Category.Find(id);
            if (tbl_Category == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Category);
        }

        // GET: Category/Create
        public ActionResult Create()
        {
            if (Session["admin"] == null) return RedirectToAction("Login");
            ViewBag.pub_id = new SelectList(db.tbl_Publisher, "id", "name");
            return View();
        }

        // POST: Category/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,pub_id,name,meta_name,amount")] tbl_Category tbl_Category)
        {
            if (Session["admin"] == null) return RedirectToAction("Login");
            if (ModelState.IsValid)
            {
                db.tbl_Category.Add(tbl_Category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.pub_id = new SelectList(db.tbl_Publisher, "id", "name", tbl_Category.pub_id);
            return View(tbl_Category);
        }

        // GET: Category/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["admin"] == null) return RedirectToAction("Login");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Category tbl_Category = db.tbl_Category.Find(id);
            if (tbl_Category == null)
            {
                return HttpNotFound();
            }
            ViewBag.pub_id = new SelectList(db.tbl_Publisher, "id", "name", tbl_Category.pub_id);
            return View(tbl_Category);
        }

        // POST: Category/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,pub_id,name,meta_name,amount")] tbl_Category tbl_Category)
        {
            if (Session["admin"] == null) return RedirectToAction("Login");
            if (ModelState.IsValid)
            {
                db.Entry(tbl_Category).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.pub_id = new SelectList(db.tbl_Publisher, "id", "name", tbl_Category.pub_id);
            return View(tbl_Category);
        }

        // GET: Category/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["admin"] == null) return RedirectToAction("Login");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Category tbl_Category = db.tbl_Category.Find(id);
            if (tbl_Category == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Category);
        }

        // POST: Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Session["admin"] == null) return RedirectToAction("Login");
            tbl_Category tbl_Category = db.tbl_Category.Find(id);
            db.tbl_Category.Remove(tbl_Category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

demo/Views/Shared/Admin.cshtml
@{ 
    demo.Models.tbl_Admin ad = (demo.Models.tbl_Admin)Session["admin"];
}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>Admin</title>

    <!-- Fontfaces CSS-->
    <link href="~/Content/CoolAdmin-master/css/font-face.css" rel="stylesheet" />
    <link href="~/Content/CoolAdmin-master/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <link href="~/Content/CoolAdmin-master/vendor/font-awesome-5/css/fontawesome-all.min.css" rel="stylesheet" media="all">
    <link href="~/Content/CoolAdmin-master/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="~/Content/CoolAdmin-master/vendor/bootstrap-4.1/bootstrap.min.css" rel="stylesheet" media="all">

    <!-- Vendor CSS-->
    <link href="~/Content/CoolAdmin-master/vendor/animsition/animsition.min.css" rel="stylesheet" media="all">
    <link href="~/Content/CoolAdmin-master/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet" media="all">
    <link href="~/Content/CoolAdmin-master/vendor/wow/animate.css" rel="stylesheet" media="all">
    <link href="~/Content/CoolAdmin-master/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" media="all">
    <link href="~/Content/CoolAdmin-master/vendor/slick/slick.css" rel="stylesheet" media="all">
    <link href="~/Content/CoolAdmin-master/vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="~/Content/CoolAdmin-master/vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="~/Content/CoolAdmin-master/css/theme.css" rel="stylesheet" media="all">

</head>

<body class="animsition">
    <div class="page-wrapper">
        <!-- MENU SIDEBAR-->
        <aside class="menu-sidebar d-none d-lg-block">
            <div class="logo">
                <a href="#">
                    <img src="~/Content/CoolAdmin-master/images/icon/logo.png" alt="Cool Admin" />
                </a>
            </div>
            <div class="menu-sidebar__content js-scrollbar1">
                <nav class="navbar-sidebar">
                    <ul class="list-unstyled navbar__list">
                        <li>
                            <a href="@Url.Action("Home","Admin")">
                                <i class="fas fa-home"></i>Home
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","Publisher")">
                                <i class="fas fa-industry"></i>Publisher
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","Category")">
                                <i class="fas fa-list-ul"></i>Category
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","Product")">
                                <i class="fab fa-product-hunt"></i>Product
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","Bill")">
                                <i class="fas fa-calculator"></i>Bill
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","Admin")">
                                <i class="fas fa-child"></i>Admin
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","Customer")">
                                <i class="fas fa-address-card"></i>Customer
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </aside>
        <!-- END MENU SIDEBAR-->
        <!-- PAGE CONTAINER-->
        <div class="page-container">
            <!-- HEADER DESKTOP-->
            <header class="header-desktop">
                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        <div class="header-wrap">
                            <form class="form-header" action="" method="POST"></form>
                            <div class="header-button">
                                <div class="account-wrap">
                                    <div class="account-item clearfix js-item-menu">
                                        <div class="image">
                                            <img src="~/Content/CoolAdmin-master/images/icon/avatar-01.jpg" alt="@ad.username" />
                                        </div>
                                        <div class="content">
                                            <a class="js-acc-btn" href="#">@ad.name</a>
                                        </div>
                                        <div class="account-dropdown js-dropdown">
                                            <div class="info clearfix">
                                                <div class="image">
                                                    <a href="#">
                                                        <img src="~/Content/CoolAdmin-master/images/icon/avatar-01.jpg" alt="@ad.username" />
                                                    </a>
                                                </div>
                                                <div class="content">
                                                    <h5 class="name">
                                                        <a href="#">@ad.name</a>
                                                    </h5>
                                                    
                                                </div>
                                            </div>
                                            <div class="account-dropdown__footer">
                                                <a href="@Url.Action("Logout","Admin")">
                                                    <i class="zmdi zmdi-power"></i>Logout
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- HEADER DESKTOP-->
            <div class="main-content">
                <div class="section__content section__content--p30">
                    @RenderBody()
                </div>
            </div>
            <!-- END PAGE CONTAINER-->
        </div>

            </div>

            <!-- Jquery JS-->
            <script src="~/Content/CoolAdmin-master/vendor/jquery-3.2.1.min.js"></script>
            <!-- Bootstrap JS-->
            <script src="~/Content/CoolAdmin-master/vendor/bootstrap-4.1/popper.min.js"></script>
            <script src="~/Content/CoolAdmin-master/vendor/bootstrap-4.1/bootstrap.min.js"></script>
            <!-- Vendor JS       -->
            <script src="~/Content/CoolAdmin-master/vendor/slick/slick.min.js">
            </script>
            <script src="~/Content/CoolAdmin-master/vendor/wow/wow.min.js"></script>
            <script src="~/Content/CoolAdmin-master/vendor/animsition/animsition.min.js"></script>
            <script src="~/Content/CoolAdmin-master/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js">
            </script>
            <script src="~/Content/CoolAdmin-master/vendor/counter-up/jquery.waypoints.min.js"></script>
            <script src="~/Content/CoolAdmin-master/vendor/counter-up/jquery.counterup.min.js">
            </script>
            <script src="~/Content/CoolAdmin-master/vendor/circle-progress/circle-progress.min.js"></script>
            <script src="~/Content/CoolAdmin-master/vendor/perfect-scrollbar/perfect-scrollbar.js"></script>
            <script src="~/Content/CoolAdmin-master/vendor/chartjs/Chart.bundle.min.js"></script>
            <script src="~/Content/CoolAdmin-master/vendor/select2/select2.min.js">
            </script>

            <!-- Main JS-->
            <script src="~/Content/CoolAdmin-master/js/main.js"></script>
            @RenderSection("Scripts", required: false)

</body>

</html>
<!-- end document-->

demo/Views/Shared/Cart.cshtml
<!-- cart box -->
<div class="aa-cartbox">
    <a class="aa-cart-link" href="#">
        <span class="fa fa-shopping-basket"></span>
        <span class="aa-cart-title">SHOPPING CART</span>
        <span class="aa-cart-notify">2</span>
    </a>
    <div class="aa-cartbox-summary">
        <ul>
            <li>
                <a class="aa-cartbox-img" href="#"><img src="img/woman-small-2.jpg" alt="img"></a>
                <div class="aa-cartbox-info">
                    <h4><a href="#">Product Name</a></h4>
                    <p>1 x $250</p>
                </div>
                <a class="aa-remove-product" href="#"><span class="fa fa-times"></span></a>
            </li>
            <li>
                <a class="aa-cartbox-img" href="#"><img src="img/woman-small-1.jpg" alt="img"></a>
                <div class="aa-cartbox-info">
                    <h4><a href="#">Product Name</a></h4>
                    <p>1 x $250</p>
                </div>
                <a class="aa-remove-product" href="#"><span class="fa fa-times"></span></a>
            </li>
            <li>
                <span class="aa-cartbox-total-title">
                    Total
                </span>
                <span class="aa-cartbox-total-price">
                    $500
                </span>
            </li>
        </ul>
        <a class="aa-cartbox-checkout aa-primary-btn" href="@Url.Action("Checkout","Home")">Checkout</a>
    </div>
</div>
<!-- / cart box -->